spring:
  datasource:
    url: jdbc:mysql://localhost/kiepersol
    username: liza
    password: diesel
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
